/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/players/register": {
    /**
     * registers a new player 
     * @description Registers a new player to the game
     */
    post: operations["registerPlayer"];
  };
  "/v1/players/me": {
    /** Get the current player */
    get: operations["getMe"];
    /** Options route for CORS */
    options: operations["getMeCors"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Player: {
      /**
       * Format: uuid 
       * @example d290f1ee-6c54-4b01-90e6-d701748f0851
       */
      id: string;
      /** @example Player One */
      name: string;
      /** @example 5 */
      score: number;
    };
    RegisterPlayerRequest: {
      /** @example Player One */
      name: string;
    };
    RegisterPlayerResponse: {
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c */
      accessToken: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  registerPlayer: {
    /**
     * registers a new player 
     * @description Registers a new player to the game
     */
    /** @description Player to register */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["RegisterPlayerRequest"];
      };
    };
    responses: {
      /** @description player registered */
      201: {
        content: {
          "application/json": components["schemas"]["RegisterPlayerResponse"];
        };
      };
      /** @description invalid input, object invalid */
      400: never;
    };
  };
  getMe: {
    /** Get the current player */
    responses: {
      /** @description Player details */
      200: {
        content: {
          "application/json": components["schemas"]["Player"];
        };
      };
      /** @description Unauthorized */
      401: never;
    };
  };
  getMeCors: {
    /** Options route for CORS */
    responses: {
      /** @description CORS response */
      200: never;
    };
  };
}
