/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/prices": {
    /**
     * get the price of bitcoin 
     * @description Get the price of bitcoin in USD
     */
    get: operations["getPrice"];
    /** Options route for CORS */
    options: operations["getPriceCors"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CoinPrice: {
      /** @example 1467.24 */
      value: number;
      /** @example "2022-11-25T12:00:00.000Z" */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  getPrice: {
    /**
     * get the price of bitcoin 
     * @description Get the price of bitcoin in USD
     */
    responses: {
      /** @description bitcoin price in usd */
      200: {
        content: {
          "application/json": components["schemas"]["CoinPrice"];
        };
      };
      /** @description Unauthorized */
      401: never;
      /** @description Not found */
      404: never;
    };
  };
  getPriceCors: {
    /** Options route for CORS */
    responses: {
      /** @description CORS response */
      200: never;
    };
  };
}
