/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/guesses": {
    /** get the active guess */
    get: operations["getActiveGuess"];
    /** creates a guess */
    post: operations["createGuess"];
    /** Options route for CORS */
    options: operations["guessesCors"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Guess: {
      /**
       * Format: uuid 
       * @example d290f1ee-6c54-4b01-90e6-d701748f0851
       */
      playerId: string;
      /**
       * @example up 
       * @enum {string}
       */
      direction: "up" | "down";
      /** @example 1235.7 */
      priceWhenCreated: number;
      /** @example "2022-11-25T12:00:00.000Z" */
      createdAt: string;
    };
    CreateGuessRequest: {
      /**
       * @example up 
       * @enum {string}
       */
      direction: "up" | "down";
    };
    ActiveGuess: {
      activeGuess?: components["schemas"]["Guess"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  getActiveGuess: {
    /** get the active guess */
    responses: {
      /** @description Active guess */
      200: {
        content: {
          "application/json": components["schemas"]["ActiveGuess"];
        };
      };
      /** @description Unauthorized */
      401: never;
    };
  };
  createGuess: {
    /** creates a guess */
    /** @description The guess to make */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CreateGuessRequest"];
      };
    };
    responses: {
      /** @description guess created */
      201: {
        content: {
          "application/json": components["schemas"]["Guess"];
        };
      };
      /** @description invalid input, object invalid */
      400: never;
      /** @description Unauthorized */
      401: never;
      /** @description Conflict, there is already a guess */
      409: never;
      /** @description Current price is not available */
      503: never;
    };
  };
  guessesCors: {
    /** Options route for CORS */
    responses: {
      /** @description CORS response */
      200: never;
    };
  };
}
